language: node_js
node_js:
  - "6"

env:
  - TRAVIS_CI=1

cache:
  yarn: true
  directories:
    - node_modules

install:
  npm i

script:
  - npm run lint
  - npm run build
  - npm test
  - npm run typescript-test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/site
  on:
    branch: master

notifications:
  slack: eleme:3Nouwh5OgNugxccCsiFYpUIB
