language: node_js
node_js:
  - "6"

env:
- TRAVIS_CI=1

cache:
  directories:
    - node_modules

install:
  npm i

script:
  - npm run lint
  - npm run build
  - npm test

notifications:
  slack: eleme:3Nouwh5OgNugxccCsiFYpUIB
